name: meet

services:
  meet-database:
    image: postgres:15
    container_name: meet-database
    restart: always
    volumes:
      - ./database-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: xMeet
      PGPORT: 5433
    networks:
      - meet-network
    ports:
      - 5434:5434
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      retries: 10
      timeout: 5s

  meet-server:
    container_name: meet-server
    build:
      context: ../
      dockerfile: infrastructure/development.Dockerfile
    volumes:
      - .:/usr/app
      - .env.development:/usr/app/.env.development
      - /usr/app/node_modules
    ports:
      - 3006:3006
      - 8083:8083
    networks:
      - meet-network
    environment:
      NODE_ENV: development
    env_file:
      - .env.development
    depends_on:
      meet-database:
        condition: service_healthy

networks:
  meet-network:
    name: meet
