name: Pre build ( Health check )
on:
    push:
        branches:
          - 'master'
    pull_request:
        branches:
          - 'master'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn install
            - name: Build
              run: yarn build
